[project]
name = "wallets-backend"
version = "0.1.0"
description = "Backend servis za upravljanje i distribuciju digitalnih ulaznica."
readme = "README.md"
requires-python = ">=3.14,<3.15"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
]

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "app"
module-root = "src"
